### ISSUE TITLE
Local Network Traversal - Multicast Discovery, Hairpinning, PMP, PCP

### ISSUE THREAD

**Issue by joshuakarp** [MatrixAI/js-mdns#1]
_Created by @CMCDragonkai_ 
### Specification
![Untitled-2023-06-09-1740](https://github.com/MatrixAI/js-mdns/assets/50583248/5450cc32-4572-4a4d-bfed-51c6e8cd04e2)
There are two types of Data Flow in the MDNS System, Polling (Pull), and Announcements/Responses (Push). When a Node joins the MDNS group, the records are pushed to all other nodes. However, for the joined node to discover other nodes, it needs to conduct polling queries that other nodes respond to.

#### Sending Queries
![image](https://github.com/MatrixAI/js-mdns/assets/50583248/21305a4c-db91-4036-9ac9-0943c84f9c7b)
The MDNS spec states that query records can have additional records, but we won't care to do this as it isn't necessary.
Queries won't have any other records in the query record, much like a standard DNS packet (albeit an mdns query packet can contain multiple questions).

In the case that a responder is binded to 2 interfaces that are connected to the same network (such as a laptop with WiFi + ethernet connected), the queries asking for the ip for a hostname of the responder will receive multiple responses with different ip addresses.
![Untitled-2023-06-09-1740 excalidraw](https://github.com/MatrixAI/js-mdns/assets/50583248/52e79a92-e646-4862-acc5-c14830ab59c5)

This behavior is documented in: [RFC 6762 14.](https://datatracker.ietf.org/doc/html/rfc6762#section-14)

##### Control Flow
~~Unlike other mDNS libraries, we're going to use an AsyncIterator in order to have the consumer to have more control over the querying. An example of this would be:~~

```typescript
async function* query({...}: Service, minimumDelay: number = 1, maximumDelay: number = 3600) {
   let delay = minimumDelay;
   while (true) {
    await this.sendPacket(...);
    delay *= 2;
    yield delay;
  }
}
```
The query system has been decided to have it's runtime contained within `MDNS` rather than being consumer-driven. This means that scheduled background queries will have to be managed by a TaskManager (similar to polykey)

##### Data Flow
![Untitled-2023-06-09-1740(1)](https://github.com/MatrixAI/js-mdns/assets/50583248/aad26c1e-4980-4dab-88e1-ea748e4f8b1f)

##### Data Flow
Because queries are basically fire and forget, the main part comes in the form of receiving query responses from the multicast group. Hence, our querier needs to be able to collect records with a fan-in approach using a muxer that is reactive:

![Untitled-2023-06-09-1740(3)](https://github.com/MatrixAI/js-mdns/assets/50583248/c36f1378-54f1-4442-bf55-d52f9b64f043)

This can also be interpreted as a series of state transitions to completely build a service.
![Untitled-2023-06-09-1740(3)](https://github.com/MatrixAI/js-mdns/assets/50583248/054de63d-d92c-439d-949c-7e1871e66f5d)

There also needs to be consideration that if the threshold for a muxer to complete is not reached, that additional queries are sent off in order to reach the finished state.
![Untitled-2023-06-09-1740(2)](https://github.com/MatrixAI/js-mdns/assets/50583248/5cbb95f9-1447-4b86-a3ed-493c59823822)

The decision tree for such would be as follows:
![Untitled-2023-06-09-1740(4)](https://github.com/MatrixAI/js-mdns/assets/50583248/ff51fa3e-2a1a-48c4-add0-aab0a52c932d)

##### Control Flow
Instances of MDNS will extend EventTarget in order to emit events for service discovery/removal/etc.
```typescript
class MDNS extends EventTarget {
}
```

The cache will be managed using a timer that is set to the soonest record TTL, rather than a timer for each record. The cache will also need to be an LRU in order to make sure that malicious responders cannot overwhelm it.

##### Control Flow
This will need to be experimented with a little. Currently the decisions are:
- registerService cannot be called before start is called.
- create should take in services in place of this.
- stop should deregister all services
- destroy should remove everything from the instance
```typescript
class MDNS extends EventTarget {
  create()
  start()
  stop()
  register()
  deregister()
}
```

#### Types
Messages can be Queries or Announcements or Responses.
This can be expressed as:
```typescript
type MessageType = "query" | "announcement" | "response";
type Message = [MessageType, ResourceRecord] & ["query", QuestionRecord];
const message = ["query", {...}];
```

#### Parser / Generator
The Parsing and Generation together are not isomorphic, as different parsed UInt8array packets can result in the same packet structure.

Every worker parser function will return the value wrapped in an object of this type:
```typescript
type Parsed<T> = {
  data: T;
  remainder: UInt8Array;
}
```

The point of this is so that whatever hasn't been parsed get returned in `.remainder` so we don't keep track of the offset manually. This means that each worker function also needs to take in a second uint8array representing the original data structure.
1. DNS Packet Parser Generator Utilities
  - Parser - `parsePacket(Uint8array): Packet`
    - Headers - `parseHeader(Uint8array): {id: ..., flags: PacketFlags, counts: {...}}`
    - Id - `parseId(Uint8array): number`
    - Flags - `parseFlags(Uint8Array): PacketFlags`
    - Counts - `parseCount(Uint8Array): number`
    - Question Records - `parseQuestionRecords(Uint8Array): {...}`
      - `parseQuestionRecord(Uint8Array): {...}`
    - Resource Records - `parseResourceRecords(Uint8Array): {...}`
      - `parseResourceRecord(Uint8Array): {...}`
      - `parseResourceRecordName(Uint8Array): string`
      - `parseResourceRecordType(Uint8Array): A/CNAME`
      - `parseResourceRecordClass(Uint8Array): IN`
      - `parseResourceRecordLength(Uint8array): number`
      - `parseResourceRecordData(Uint8array): {...}`
        - `parseARecordData(Uint8array): {...}`
        - `parseAAAARecordData(Uint8array): {...}`
        - `parseCNAMERecordData(Uint8array): {...}`
        - `parseSRVRecordData(Uint8array): {...}`
        - `parseTXTRecordData(Uint8array): Map<string, string>`
        - `parseOPTRecordData(Uint8array): {...}`
        - `parseNSECRecordData(Uint8array): {...}`
    - String Pointer Cycle Detection 
      - Everytime a string is parsed, we take reference of the beginning and end of the string so that pointers cannot point to a start of a string that would infinite loop. A separate index table for the path of the dereferences to make sure deadlock doesn't happen.
    - Errors at each parsing function instead of letting the data view failing
      - `ErrorDNSParse` - Generic error with message that contains information for different exceptions. Ie. `id parse failed at ...`
    - Record Keys - `parseResourceRecordKey` and `parseQuestionRecordKey` and `parseRecordKey` - `parseLabels`.
  - Generator - `generatePacket(Packet): UInt8Array`
    - Header `generateHeader(id, flags, counts...)`
      - Id
      - Flags - `generateFlags({ ... }): Uint8Array`
      - Counts - `generateCount(number): Uint8Array`
    - Question Records - `generateQuestionRecords(): Uint8Array` - `flatMap(generateQuestion)`
      - `generateQuestionRecord(): Uint8Array`
    - Resource Records (KV) - `generateResourceRecords()`
      - `generateRecord(): Uint8array` - 
      - `generateRecordName` - "abc.com" - ...RecordKey
      - `generateRecordType` - A/CNAME
      - `generateRecordClass` - IN
      - `generateRecordLength`
      - `generateRecordData`
        - `generateARecordData(string): Uint8array`
        - `generateAAAARecordData(string): Uint8array`
        - `generateCNAMERecordData(string): Uint8array`
        - `generateSRVRecordData(SRVRecordValue): Uint8array`
        - `generateTXTRecordData(Map<string, string>): Uint8array`
        - `generateOPTRecordData(Uint8array): Uint8array`
        - `generateNSECRecordData(): Uint8array`
  - Integrated into `MDNS`
2. `MDNS`
  - Querying
    - `MDNS.query()`
     - query services of a type
    - `MDNS.registerService()`
    - `MDNS.unregisterService()`
  - Responding
    - Listening to queries
    - Responding to all queries with all records
    - Respond to unicast
    - Truncated bit
 
#### Testing
We can use two MDNS instances to interact with each other to test both query and respond on separate ports.

### Additional Context

The following discussion from 'Refactoring Network Module' MR should be addressed:
* @CMCDragonkai:  (+3 comments)

    > Next things:
    > 
    > 1. Multicast discovery (bring back what we had in the old code)
    > 2. Update our peer table
    > 3. Implement kademlia on peer table
    > 4. Refactor GRPC commands for this
    > 5. Produce test harness for multiple nodes on a local network
    > 
    > ## Multicast Discovery
    > 
    > DNS-SD and mDNS are related protocols for discovery on a local network. This local network is designated usually by a "home router" or a switch. But basically some arbitrary subnet with gateways that are part of a "single network".
    > 
    > The way this works is that there's a special address (for IPv4 and IPv6) that a mDNS software both listens and sends UDP packets on. This is known as a "multicast" address.
    > 
    > The UDP packet contains information structured as a "DNS message", basically the same kind of message you get when you actually query a DNS server to resolve a hostname.
    > 
    > What we have to do is register a hostname for our application. Let's say "polykey", this registration is done on IANA (just like how we registered the OID for our company). This list is here: https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml and our application for an assignment is here: https://www.iana.org/form/ports-services
    > 
    > Now once we build a multicast mDNS client/server, we can then advertise on the multicast address by sending a DNS UDP packet that claims "polykey.local" is registered to IP at PORT. Simultaneously we can listen on the multicast address for DNS packets, and filter for all claims to "polykey.local".
    > 
    > Since multiple PK agents can occur on the same subnet, this means we may either have to differentiate on a subdomain of our hostname, or append a renew record to the hostname. It is possible for a given hostname to contain multiple DNS records (and these may indicate IP and PORT assignments). I'm not sure if this is the right way to do this. Need to do a bit of research.
    > 
    > At the end of the day, PK node table gets populated with this initial multicast discovery. We have to have a mDNS client (to send multicast) and mDNS server (to listen for multicast). The mDNS server would be listening for these packets.
    > 
    > Note that there is software like avahi, that acts like an mDNS server/client, this is used interactively by other software that don't have native mDNS capabilities. This is not important to us... we will be advertising directly.
    > 
    > According to this: https://askubuntu.com/a/1105895 it may be possible that the "service type" is different from the hostname. Therefore it's possible to randomly allocate a hostname, and only listen for a given "service type". In which case `_polykey_._tcp` would be the service type, and you could get hostnames like `polykey-PUBLICKEYFINGERPRINT.local`, and thus that should be considered unique. Therefore from a service discovery point of view, the only thing static is the IP used for multicast, and the "service type" which is globally setup at IANA. The hostnames, IPs and even ports are all dynamically setup.
    > 
    > The node library https://github.com/agnat/node_mdns binds into system-level services and provides the ability to listen and query mdns packets: https://github.com/agnat/node_mdns
    > 
    > A lower level library in pure-js is here: https://github.com/mafintosh/multicast-dns that is used with https://github.com/mafintosh/multicast-dns-service-types according to this issue: https://github.com/mafintosh/multicast-dns/issues/6#issuecomment-91034709

* https://news.ycombinator.com/item?id=8229792
* https://blog.apnic.net/2022/05/03/how-nat-traversal-works-concerning-cgnats/
* https://github.com/MatrixAI/Polykey/issues/487#issuecomment-1294558470
* https://github.com/MatrixAI/Polykey/issues/487#issuecomment-1294742114
* https://support.citrix.com/article/CTX205483/how-to-accommodate-hairpinning-behaviour-in-netscaler

* mDNS RFC https://datatracker.ietf.org/doc/html/rfc6762
* DNS-SD RFC https://datatracker.ietf.org/doc/html/rfc6763
* Domain Names RFC https://datatracker.ietf.org/doc/html/rfc1035
* Extension Mechanisms for DNS RFC https://datatracker.ietf.org/doc/html/rfc6891
* NSEC RFC https://datatracker.ietf.org/doc/html/rfc3845

### Tasks
- [x] Parser - 5.5 days
  - [x] Packet Header - 0.5 days
  - [x] Packet Flags - 0.5 days
  - [x] Questions - 0.5 days
  - [x] Resource Records - 4 days
- [x] Generator 5.5 days
  - [x] Packet Header - 0.5 days
  - [x] Packet Flags - 0.5 days
  - [x] Questions - 0.5  days
  - [x] Resource Records - 4 days
- [ ] MDNSCache - 2.5 days
  - [x] Multi-Keyed Maps for ResourceRecord Querying - 0.5 days
  - [x] TTL Expiry Record Invalidation - 0.5 days
  - [x] Reverse Host to Record Mapping - 0.5 days
  - [ ] LRU to Prevent DoS - 0.5 days
  - [ ] Support use as local resource record in-memory database - 0.5 days
- [ ] TaskManager - ? days
  - [ ] Migrate to in-memory - ? days
  - [ ] Support Fixed and Random Delays for mDNS usage - 0.5 days
- [ ] MDNS - 11.5 days
  - [ ] UDP Networking Logic - 2 days
    - [ ] Socket Binding to Multiple Interfaces - 1 days
    - [ ] Error Handling - 1 days
  - [ ] Querier - 4 days
    - [ ] Service Querying - 2.5 days
      - [x] Record Aggregation for Muxxing Together Services - 0.5 days
      - [x] Querying For a Service's Missing Records - 0.5 days
      - [x] Emitting Expired Services - 0.5 days
      - [ ] Re-Querying for Expired Services - 1 days
    - [ ] Unicast 1.5 days
      - [ ] Checking for Unicast Availability - 1 days
      - [ ] Sending queries with unicast enabled - 0.5 days
  - [ ] Responder 5.5 days
    - [x] Service Registration - 0.5 days
    - [ ] Filter Messages Received from Multicast Interface Loopback  - 0.5 days
    - [ ] Responding to truncated-bit set queriers 19/6/2023 - 2 days
    - [ ] Unicast
      - [ ] Responding to Unicast Queries - 0.5 days
    - [ ] Register and Unregister Hosts based on connected/disconnected network interfaces. - 2 days

**Comment by amydevs** [comment]
The js-mdns library has been created as a TypeScript implementation of a mDNS/DNS-SD responder/advertiser/stack.

The current plan is to first release the pure TypeScript implementation. This implementation is expected to ignore any other mDNS stack running on the system, and be aware of the [issues](https://github.com/homebridge/ciao#notice-on-native-mdns-responders) regarding this.

After that has been achieved, we can add functionality to integrate with common mDNS stacks such as
- Avahi using the DBUS API
- Apple's mDNSResponder
- Win32 with C++ API Calls
- iOS/Android

**Comment by CMCDragonkai** [comment]
Yep start speccing out the expected interface and classes and methods.

**Comment by CMCDragonkai** [comment]
So basically it turns out that we will need 3 things:

1. File-based discovery using `/var/run/polykey` - for cases where PK is running on localhost, and multicast is not enabled by default for the loopback interface
2. MDNS which should work for PK agents bound to the public interfaces, and across home routers or whether routers/switches have multicast enabled
3. Providing all bound local interface IPs to the mainnet/testnet, similar to tailscale and thus end up providing a list of potential IPs to try out

Important lesson, just because you discover it, doesn't necessarily mean you can connect to it. Until decentralised relaying is possible, discovery for now gives you potential nodes that exist, but it doesn't mean you can actually connect to it. This can happen if agents are connected to loopback only... and other agents are connected on public interface, or even both. Other agents on other networks won't be able to reach it.

Network reachability is quite complex due to how complex networks themselves can be. Decentralised will enable increased connectivity into deeper agents, but that may also not be what users want, but this is something we will have to research later.

**Comment by amydevs** [comment]
Points from the RFC to implement

Responder:
- [ ] Reverse Address Mapping (Optional) https://datatracker.ietf.org/doc/html/rfc6762#section-4
- [ ] Responding Unicast Response Bit  / Responding to Unicast Queries on Port 5353 - https://datatracker.ietf.org/doc/html/rfc6762#section-5.4 / https://datatracker.ietf.org/doc/html/rfc6762#section-5.5
- [ ] Correctly Implement DNS Rules https://datatracker.ietf.org/doc/html/rfc6762#section-6
- [ ] Negative Responses https://datatracker.ietf.org/doc/html/rfc6762#section-6.1
- [ ] Truncated Bit Multiquestion Queries https://datatracker.ietf.org/doc/html/rfc6762#section-6.3

**Comment by amydevs** [comment]
Here's a JSON representation of the minimum amount of resource records required for a service to be discoverable:
```json
[
    {
        "name": "123.local",
        "type": "A",
        "class": "IN",
        "data": "192.168.1.104",
        "ttl": 120,
        "flush": true
    },
    {
        "name": "123.local",
        "type": "AAAA",
        "class": "IN",
        "data": "fe80::f137:6ff0:9dbf:c5bd",
        "ttl": 120,
        "flush": true
    },
    {
        "name": "_services._dns-sd._udp.local",
        "type": "PTR",
        "class": "IN",
        "ttl": 120,
        "data": "_polykey._udp.local",
        "flush": true
    },
    {
        "name": "_polykey._udp.local",
        "type": "PTR",
        "class": "IN",
        "ttl": 120,
        "data": "123._polykey._udp.local",
        "flush": true
    },
    {
        "name": "123._polykey._udp.local",
        "type": "TXT",
        "class": "IN",
        "ttl": 120,
        "data": [],
        "flush": true
    },
    {
        "name": "123._polykey._udp.local",
        "type": "SRV",
        "class": "IN",
        "ttl": 120,
        "data": {
            "port": 1234,
            "target": "123.local",
            "priority": 0,
            "weight": 0
        },
        "flush": true
    }
]
```

**Comment by amydevs** [comment]
Parser Structure:
```typescript
function parserTop(input_packet: UInt8Array, original_packet: UInt8Array) {
    let remaining = original_packet;
    let input = input_packet;

    const dv = new DataView(input);
    const id = dv.get(...);
    const type = dv.get(...);

    input = input.subarray(...);
    
    // Whatever left to parse is put into the input. So that we can shift the dataviews over the uint8array without copies!
    [input, original] = parsePart1(input, original);

    [input, original] = parsePart2(input, original);

   return [input, original];
}
```

**Comment by amydevs** [comment]
parsing todo:
- [ ] Change to parse/generate and create errors for each
- [ ] Change to new parser structure above
- [ ] NSECRecords / TXT/ OPT Record parsing

**Comment by CMCDragonkai** [comment]
I updated the issue above, but it's still lacking alot of the spec. The spec should fleshed out with all the pieces of the parser/generator.

As well as how the MDNS will behave in each section.

Then a task list can be created.

The spec should be tree-oriented. The task list can be a hierarchical task list.

This would be priority Monday morning.

**Comment by CMCDragonkai** [comment]
Have a look at our recent work in js-async-monitor and js-async-cancellable and maybe we can use that in MDNS in case there are concurrent state mutations.

Are there any concurrent state mutations in the MDNS code actually?

**Comment by amydevs** [comment]
> Have a look at our recent work in js-async-monitor and js-async-cancellable and maybe we can use that in MDNS in case there are concurrent state mutations.
> 
> Are there any concurrent state mutations in the MDNS code actually?

the building of a service could be counted as a concurrent state mutation maybe?

**Comment by CMCDragonkai** [comment]
> currently i've got the querying implemented by just parsing responses, adding records to a cache, and checking what records are missing according to the cache, and querying for them. If i get a response with the records i require, i collate all the records in the cache regarding a service, and emit it on the MDNS instance, if not, no-op. (roughly following decision tree above).
> 
> However, to treat a service as a state that transitions into itself, i think it might be more suitable to create a class that represents a service, and use something like a builder pattern.

I believe your "service" should be a POJO, not an class/object. You want to keep it as simple as possible here. And it's perfectly possible to build out the POJO dataflow.

Make sure to separate your dataflow model from your controlflow model.

**Comment by CMCDragonkai** [comment]
As I explained on Friday, it's possible to consider that the service is always just 1 state, and all transitions transit from the same state to the same state.

It's when you break apart variations of that 1 state, is when you can start considering a much more detailed state machine.

However when dealing with a database, you have potentially infinite state. This means you cannot use a finite state machine to represent it since you don't have a "finite" set of states.

The way to get around this is to encapsulate the infinite-ness somewhere so it's no longer observable, or considered within the model. (All models are maps, and they all drop detail). By doing this, you can have a finite model that represents the important control flows but not it won't show the "unimportant details".

Use models as a way of doing abstract reasoning.

**Comment by CMCDragonkai** [comment]
@amydevs any update on the API since, you are now going to use something like `startQuery` and `stopQuery`.

And how are you going to incorporate the `Task` type from `TaskManager`?

Plus what about the insertion sort?

**Comment by CMCDragonkai** [comment]
The multicast system is like a broadcast within the multicast. While this library can default to the standard MDNS group address. In PK we should select a MDNS group address that is unlikely to be used by other MDNS stacks.

**Comment by amydevs** [comment]
- The dns packet parser has been finished. 
- Service registration is possible and can be resolved from other mDNS responders like Bonjour and Avahi. 
- Services on the local network can also be constructed from incoming responses and announcements.

**Comment by CMCDragonkai** [comment]
@amydevs you still have to update all the expected dates above to 0.5/1 day increments.

**Comment by CMCDragonkai** [comment]
I've updated the entire project to align with the project structure in other projects now.

**Comment by CMCDragonkai** [comment]
We're still pushing to staging atm. So eventually it will need to be squash rebased.

**Comment by CMCDragonkai** [comment]
The `index.ts` was missing all major exports.

@amydevs make sure you're reviewing all my commits from this the last one so you're aware of the situation.

**Comment by CMCDragonkai** [comment]
In `MDNS.start`:

```
    hostname = `${os.hostname()}.local` as Hostname,
```

Is used as a parameter.

However if you expect the user to put in the hostname fully, you would not expect a `.local` to exist.

So instead you should take `hostname = os.hostname() as Hostname`.

Then add the `.local` afterwards as per the MDNS spec.

**Comment by CMCDragonkai** [comment]
Some relevant discussion about sockets and interfaces and IPs:

![Network Sockets](https://github.com/MatrixAI/js-mdns/assets/640797/fbd2410c-f792-402f-8f42-ab2ef14070e4)

And https://chat.openai.com/share/0b86282d-7073-41c5-ba97-40de9902ae01

**Comment by CMCDragonkai** [comment]
So the reason we need multiple sockets (1 for each interface) when dealing with `::`, because when we receive a packet on the multicast group. We only want to respond via unicast or multicast on the interface that we received the packet from.

If we used a single socket for `::`, then we would end up sending a response to all interfaces, even if those interfaces are not on the same network.

This is why even when binding to wildcard, we need to use multiple interfaces.

**Comment by CMCDragonkai** [comment]
Found out that IPv6 interfaces might have a link local address.

In that case when using `::` or `::0` we need to detect if the address has `fe80::` as the starting prefix, then attach the `%interfacename` to the end of the `Host` string.

Otherwise it's not possible to bind to them as well with an additional socket.

Also made me realise that for a given deployment of the MDNS stack we end up creating quite a few sockets.

**Comment by tegefaulkes** [comment]
If I recall, there's also the prefix `fd00` and `fc00` for local and private network IPv6 addresses.

**Comment by CMCDragonkai** [comment]
I'm not sure if they suffer from the same problems with binding however.

@amydevs I've been working on a generic table data structure: https://github.com/MatrixAI/js-table

If it works well, perhaps we switch to using it since it seems like a common occurrence. Let me know if the API suits the MDNS cache.

**Comment by CMCDragonkai** [comment]
@amydevs js-table can be used at 1.0.0 pending release https://gitlab.com/MatrixAI/open-source/js-table/-/pipelines

**Comment by CMCDragonkai** [comment]
There was a commit that I forgot to push before.

I removed the `type` getter. It didn't make sense because `MDNS` could have multiple sockets, each with different types.

At the same time, if you are binding to ipv4, you get ipv4 type, ipv6 to ipv6 type, and if you use ipv4 mapped ipv6... I forgot what the type should be, but it should be the same as whatever js-quic does.

Furthermore each socket object should have `type`, `host` and `port` properties attached.

This means something like this:

![image](https://github.com/MatrixAI/js-mdns/assets/640797/235d7ccf-08c2-41c3-9882-56fa63dc16e0)

**Comment by CMCDragonkai** [comment]
Releasing 1.1.0 with the iterator changed to give you `[number, R]` this gives you access to the row index too. So you can delete things while iterating. Can be useful for limiting the cache size.

Also the table indexes options supports hashing functions. The default hashing function has changed to now support `null` and `undefined`. But you can provide your own hashing function.. Prefer producing a string, unless you have a specific reason.

**Comment by CMCDragonkai** [comment]
Should also create your own special `type XRow` type. Where `X` is the thing you are putting into the table. This `XRow` type can be flattened as much as possible, that way you're able to index whatever deep keys you want.

**Comment by amydevs** [comment]
i've moved and renamed MDNSCache to ResourceRecordCache to a separate folder to better reflect what it actually does. The reason for moving it to a separate folder is so that i can separate the utils, events, and errors for the cache

**Comment by amydevs** [comment]
What's left is:
- Splitting responses to separate interfaces
- Managing promises

**Comment by amydevs** [comment]
https://github.com/nodejs/node/issues/1690#issuecomment-224878448

After all, it seems that it is impossible to receive multicast messages from a socket directly binded to a specific interface. This makes things alot more complicated...

My plan is just to focus on multicast for now. So we can bind onto the multicast group address, then use setMulticastInterface and addMembership targetting specific interface addresses in order to have a separate socket (and hence handler) for each interface. 

However, only multicast messages will be able to be received on those sockets. Hence, unicast sockets also need to be binded later if we need them...

**Comment by CMCDragonkai** [comment]
Does this mean 2 sockets for every IP address?

**Comment by amydevs** [comment]
> Does this mean 2 sockets for every IP address?

yes, but that is if we decide to do unicast response, request.

**Comment by CMCDragonkai** [comment]
We're going to have to do it the way ciao does it. 1 socket per interface, but bound to wildcard.

Make sure that the sockets will be able to join both the IPv4 multicast group and IPv6 multicast group.

**Comment by amydevs** [comment]
Some tests to consider:
- DNS Packet Parsing/Generating
- Cache Insertion
- Cache Querying
- Cache Expiry
- Cache Overload
- Creating/Receiving Announcements
  - Cancelling Announcements (via stop())
- Creating/Receiving Responses
- Creating/Receiving Queries
  - Cancelling Queries
- Creating/Receiving Unicast Response
- Port Conflict

**Comment by CMCDragonkai** [comment]
@amydevs

1. Logging should use `INFO` for most things. The only warnings right now should only be for when `os.networkInterfaces` provide invalid information and when you can proceed.
2. Use `X, Xing, Xed` for the logging first keyword. Where `X` is the verb. Only using `Xing` when it's a one-off thing. `X, Xed` is for pre-X and post-X respectively.
3. Mock testing just means mocking the input/output to MDNS. We don't need to simulate multiple interfaces or multiple sockets. But by controlling the input/output, we can simulate an entire interaction of `MDNS` in different scenarios.

**Comment by amydevs** [comment]
On linux, due to node setting the `IP_MULTICAST_ALL` flag to true, will have sockets bound to any wildcard address (`::`, `::0`, `0.0.0.0`) receive all multicast traffic from all added groups on the system! This is not the same behavior as that on windows/macos/bsd. 

https://github.com/acassen/keepalived/issues/952

**Comment by CMCDragonkai** [comment]
Note that here https://github.com/clshortfuse/node-getsockethandleaddress it indicates that you can get the sockfd integer just by doing `socket._handle.fd`. Specifically for linux and macos I think.

You should confirm if this fix is needed for macos.

You'll still need to write the NAPI code to actually do something with that file descriptor number.

The `_handle.fd` does come with some sort of warning message. See if you can suppress that...?

**Comment by amydevs** [comment]
The intended behavior is that a binded socket to "0.0.0.0" or "::0", with IP_MULTICAST_ALL disabled, will not receive any multicast messages at all.
Furthermore, when addMembership is called specifying a specific interface, multicast packets will only be received from that group on that interface.

It would seem, that disabling IP_MULTICAST_ALL works as intended on udp4 sockets.

However, it seems that when disabling IPV6_MULTICAST_ALL, without calling addMembership, it works as intended.
However, as soon as I call addMembship, that socket seems to start receiving multicast packets from every interface even when i've only specified one specific interface.

**Comment by amydevs** [comment]
it seems that there are several options that add an ipv6 socket to a multicast group, being IPV6_JOIN_GROUP and IPV6_ADD_MEMBERSHIP. They all use the ipv6_mreq struct as a configuration option rather than the ip_mreq struct.

The key difference between these is that ipv6_mreq takes in the interface index, whilst ip_mreq takes an interface ip address. 

Node, upon calling addMembership, will call uv_udp_set_membership with JOIN_GROUP, passing in the interface ip address.
If it is udp4, libuv will throw ENODEV when an iface does not correspond to the address you have provided.
However, on udp6, libuv tries to look for the index of the interface with the address you've provided. However, it does not error when you give it an invalid iface ip.

**Comment by amydevs** [comment]
i've found that IP_BLOCK_SOURCE also exists. this could be useful in filtering out our own traffic. However, we would need to implement a platform-agnostic solution if we wanted to use this across all platforms. For now, having a set ip to filter out seems fine to me.

**Comment by amydevs** [comment]
as a workaround to https://github.com/MatrixAI/js-mdns/issues/1#issuecomment-1637365999, i'm trying to just bind a unicast socket first, then binding all the multicast sockets after. This is done so that the first unicast socket will catch all of the necessary unicast traffic.

I'm at the point of implementing this. However, even though i've made sure that the unicast socket is the first thing to be binded on a particular port, as soon as i bind other sockets, none of the sockets seem to be receiving any unicast traffic at all!

**Comment by amydevs** [comment]
on macos, tests run correctly, just some counted references are making the cleanup (afterAll) of MDNS hang. I've pinned it down to the sending of the goodbye packets, but i'm still figuring a solution

**Comment by amydevs** [comment]
on windows, it is not possible to bind to a multicast address like you can on any unix system. On windows systems, i am binding each multicast socket to "::" instead. This functionally is the same as binding to the multicast address in my case, as i'm binding a unicast socket before all the other multicast sockets are binded. Windows makes sure that only the first socket that you've bound will receive multicast traffic.

**Comment by CMCDragonkai** [comment]
Merged into staging now, doing the release.

**Comment by tegefaulkes** [comment]
Is this fully addressed by MDNS? Are there still plans to handle Hairpinning, PMP and PCP?

**Comment by CMCDragonkai** [comment]
PMP and PCP should be done separately.

Hairpinning not sure how that would be achieved.

**Comment by CMCDragonkai** [comment]
I created https://github.com/MatrixAI/Polykey/issues/536 to track PCP/PMP via UPNP. I did find a project that could be wrapped around in JS to make use of.

**Comment by CMCDragonkai** [comment]
@amydevs please tick off everything that was done above too.
